name: Build & Test

on:

  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  buildandtest:
    name: "Build & Test"
    # if: ${{ github.event.lint.conclusion == 'success' }}
    needs: [lint]
    strategy:
      matrix:
        go: [ '1.22' ]
        os: [ 'ubuntu-latest', 'macOS-latest' ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: "Setup Git Project"
        uses: actions/checkout@v4

      - name: "Setup Go Env"
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version: ">=1.22"
          # go-version: ${{ matrix.go }}

      - name: "Check Go Dependencies"
        run: go mod tidy

      - name: "Build"
        run: go build -v ./...

      - name: "Check Go Tests"
        run: go test -v -race ./... -coverprofile=coverage.txt -covermode=atomic -timeout=90s
        # run: go test -v -cover -race -timeout 60s ./...

      - name: "Check Go Formatting"
        run: |
          test -z $(gofmt -l -s .)

      - name: Codecov
        uses: codecov/codecov-action@v4
        if: matrix.os == 'ubuntu-latest'
