name: Typo Check

on: [workflow_call]

jobs:
  typocheck:
    name: "Typo Check"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: typos-action
      uses: crate-ci/typos@v1.41.0